### ISSUE TITLE
mods 目录的特殊设计

### ISSUE THREAD

**Issue by DesistDaydream** [WH-2099/dst-server#4]
[这里](https://github.com/WH-2099/dst-server/blob/dfa00a6c9b80111ba70eefc8312785d0a5d2ce7b/entrypoint.sh#L59) 会导致在遍历时把 mods/ 目录也算进去，提示找不到 server.ini 文件。

如果在 mods/ 目录下加了 server.ini 程序就会忽略 Master，把 mods 当作主世界启动。

**Comment by WH-2099** [comment]
#### 解决方案

你可以放心的删除 `/cluster` 下的 `mods` 目录，启动脚本会自行管理这个目录。

#### 背景原因

1. 这个项目更多地是专门为单机运行多房间设计的，为了方便单点维护，服务端目录其实是本地挂载共享的（当然如果不挂载，它依然可以正常运行，只是房间（容器）多了以后就需要每个都去升级）。
2. `mods` 文件夹是一个比较蛋疼的东西，目前它更偏向于 Klei 开发团队早期的“技术债”，它的路径位于游戏服务端目录下，这不符合 steam 推荐的做法。
3. 后续 Klei 开发团队也做了补救，新的 mod 都会按照 steam 的新创意工坊组件，安装在 `ugc` 目录下（容器内就是 `/ugc`）。
4. 目前 `mods` 目录中实际有效的文件就两种：
    - `dedicated_server_mods_setup.lua` mod 加载脚本
    - 非常老且失去维护的 mod

在以上前提下，这里的设计是将挂载的 `/install` 目录下创建软连接 `mods` 指向容器内的 `/mods`，从而实现各容器都拥有自己独立的 `mods`，同时启动脚本会自行识别并动态编写 `dedicated_server_mods_setup.lua` 脚本。

**Comment by WH-2099** [comment]
如果你希望将模组相关文件也持久化到本地（对于大型 mod 很有用，后续更新镜像也不需要重新下载 mod)，可以额外挂载容器内的 `/ugc` 目录，这个是当前主要的 mod 文件存储位置。

**Comment by DesistDaydream** [comment]
非常感谢你的耐心解答。我之前想研究 steam 的一些最佳实践，尤其是了解一些生态，比如目录结构的最佳实践之类的，在 [SteamCMD Wiki](https://developer.valvesoftware.com/wiki/SteamCMD) 只看到了大概，但是说来惭愧，一直没找到类似那些开源项目文档的 Steam 文档。。。。昨天我在实验另一个 [DST 项目](https://github.com/Jamesits/docker-dst-server) 看到了 ugc 目录，你这也提到之后，我搜了一下，是 User Generated Content，但是依然没找到 Steam 的官方文档。。都是社区文章之类的。昨天弄 Mods 遇上了 `[Workshop] ODPF failed entirely: 37` 报错，一会惦记研究一下。

冒昧咨询一下，咱平时了解这些内容是从哪个网站看的？我不管是用 steam developer documentation 还是 steam documentation 这种关键字搜索，那些网站很多都不像是看到一些与开发相关内容的文章。比如 steamcmd 安装后一般都有什么目录结构，目录中都对应什么内容。

虽然我可以像下面这样根据自己经验可以一点点总结。。但是总觉得应该有个官方文档
![image](https://github.com/user-attachments/assets/dd9a13b4-ee96-407b-9ce5-a8eef96e5cd1)

**Comment by WH-2099** [comment]
根据你的提纲，这里面其实包含了两个层级的内容。

#### Steam

Steam 的生态目前是非常庞大和复杂的，也有详尽的文档，例如：
https://partner.steamgames.com/doc/features/workshop/implementation


#### DST 服务端

Steam 更多地只是提供底层框架，每款游戏都会有其独立的上层封装和实现，饥荒联机版也是如此，所以更多地还是需要从 Klei 论坛获取详细的内容，例如：
https://forums.kleientertainment.com/forums/topic/64743-dedicated-server-command-line-options-guide/

**Comment by DesistDaydream** [comment]
非常感谢 O(∩_∩)O，用咱的镜像已经可以基本正常运行了，我使用了如下目录结构

```bash
$ tree compose/dst/dst-server/
compose/dst/dst-server/
├── cluster
│   ├── Caves
│   │   ├── leveldataoverride.lua
│   │   ├── modoverrides.lua
│   │   └── server.ini
│   └── Master
│       ├── leveldataoverride.lua
│       ├── modoverrides.lua
│       └── server.ini
├── docker-compose.yaml
├── env.sh
├── install
├── mods
│   ├── dedicated_server_mods_setup.lua
│   └── modsettings.lua
└── ugc
```

> 如果要能直接配置世界生成的话，应该还有 worldgenoverride.lua 文件才对。我后面会再深入研究生态和常见规范，完善一下

docker-compose.yaml

```yaml
version: '3'

services:
  dst-server:
    container_name: dst
    env_file:
      - env.sh
    image: wh2099/dst-server:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./cluster:/cluster
      - ./install:/install
      - ./ugc:/ugc
      - ./mods:/mods
```

env.sh # 用于 配置代理、etc. 根据实际需要设置

```shell
http_proxy="http://192.168.254.254:7890"
https_proxy="http://192.168.254.254:7890"
all_proxy="sock5://192.168.254.254:7890"
```
